version: '3'

services:
  mongodb:
    container_name: mongodb-elency-config-server-demo
    image: mongo:3.0
    expose:
      - 27017
    logging:
      driver: none
  demo:
    #build: .
    container_name: elency-config-client-demo
    image: croweman/elency-config-demo:0.0.7-beta
    volumes:
      - configuration_files:/app/configuration_files
    depends_on:
      - mongodb
  ldapmockserver:
    container_name: elency-config-demo-ldap-mock-server
    image: croweman/elency-config-demo-ldap-mock-server:0.0.3-beta
    restart: "on-failure:10"
    ports:
      - "3001:3001"
    expose:
      - 3001
    logging:
      driver: none
  app:
    container_name: elency-config-server-demo
    image: croweman/elency-config-server:0.0.9-beta
    restart: "on-failure:10"
    volumes:
      - configuration_files:/app/configuration_files
    depends_on:
      - mongodb
      - demo
      - ldapmockserver
    ports:
      - "3000:3000"
    expose:
      - 3000
    environment:
      CONFIG_JSON_VALUE:
      KEYS_JSON_VALUE:
      PRIVATE_PEM_VALUE:
      PUBLIC_PEM_VALUE:

volumes:
  configuration_files:
