version: '3'

services:
  mongodb:
    container_name: mongodb-elency-config-server-demo
    image: mongo:3.4
    expose:
      - 27017
    logging:
      driver: none

  demo:
    #build: .
    container_name: elency-config-client-demo
    image: croweman/elency-config-demo:0.0.15-beta
    volumes:
      - configuration_files:/app/configuration_files
      - certs:/app/certs
      - status:/app/status
    depends_on:
      - mongodb

  node-client:
    #build: ./support/node-client
    container_name: elency-config-client-demo-node-client
    image: croweman/elency-config-node-client-demo:0.0.2-beta
    volumes:
      - status:/app/status
    depends_on:
      - demo
      - app

  csharp-client:
    #build: ./support/csharp-client
    container_name: elency-config-client-demo-csharp-client
    image: croweman/elency-config-csharp-client-demo:0.0.1-beta
    volumes:
      - status:/build/status
    depends_on:
      - demo
      - app

  bash-client:
    #build: ./support/bash-client
    container_name: elency-config-client-demo-bash-client
    image: croweman/elency-config-bash-client-demo:0.0.2-beta
    volumes:
      - status:/app/status
    depends_on:
      - demo
      - app

  ldapmockserver:
    container_name: elency-config-demo-ldap-mock-server
    image: croweman/elency-config-demo-ldap-mock-server:0.0.3-beta
    restart: "on-failure:10"
    ports:
      - "3001:3001"
    expose:
      - 3001
    logging:
      driver: none

  nginx-proxy:
    container_name: elency-config-server-proxy
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs
    networks:
      default:
        ipv4_address: 172.20.0.200
    depends_on:
      - demo
    logging:
      driver: none

  whoami:
    container_name: elency-config-whoami
    image: jwilder/whoami
    volumes:
      - certs:/usr/local/share/ca-certificates
    environment:
      - VIRTUAL_HOST=whoami.vcap.me
      - VIRTUAL_PORT=8000
    extra_hosts:
      - "elency-config.vcap.me:172.20.0.200"
      - "whoami.vcap.me:172.20.0.200"
    depends_on:
      - demo
    logging:
      driver: none    

  app:
    container_name: elency-config-server-demo
    image: croweman/elency-config-server:0.0.22-beta
    restart: "on-failure:10"
    volumes:
      - configuration_files:/app/configuration_files
    depends_on:
      - mongodb
      - demo
      - ldapmockserver
    environment:
      CONFIG_JSON_VALUE:
      KEYS_JSON_VALUE:
      PRIVATE_PEM_VALUE:
      PUBLIC_PEM_VALUE:
      VIRTUAL_HOST: elency-config.vcap.me
      VIRTUAL_PORT: 3000
    extra_hosts:
      - "elency-config.vcap.me:172.20.0.200"
      - "whoami.vcap.me:172.20.0.200"

volumes:
  configuration_files:
  certs:
  status:

networks:
  default:
    ipam:
      config:
        - subnet: 172.20.0.0/16
    
